import { Document, OrganizationProfile } from '../types';
import { getCurrentGregorianDate, getCurrentHijriDate } from './dateHelper';

export const initialOrganizationProfile: OrganizationProfile = {
  id: 1,
  ministryName: 'وزارة الإدارة والتنمية المحلية والريفية',
  administrationName: 'صندوق النظافة والتحسين م/إب',
  branchName: 'فرع مديرية الحزم',
  address: 'محافظة إب - مديرية الحزم - الجمهورية اليمنية',
  phone: '04-456789 / 771234567',
  managerName: 'رياض احمد محمد',
  managerTitle: 'مدير فرع صندوق النظافة',
  financeManagerName: '', // يترك فارغاً ليتم إضافته في المحرر
  financeManagerTitle: 'المدير المالي للفرع',
  auditorName: '',
  treasurerName: '', // يترك فارغاً ليتم إضافته في المحرر
  treasurerTitle: 'أمين الصندوق',
  systemFooterNote: 'طبع بواسطة نظام مالية فرع صندوق النظافةوالتحسين مديرية الحزم',
};

export const DEFAULT_TAG_SUGGESTIONS: string[] = [
  'كهرباء',
  'صيانة',
  'رواتب',
  'وقود ومحروقات',
  'أجور عمال',
  'مستلزمات مكتبية',
  'قطع غيار',
  'نظافة',
  'ضيافة',
  'إيجار',
  'معدات',
];

export const sampleDocuments: Document[] = [
  {
    id: 'doc-1',
    type: 'ORDER',
    documentNumber: '0001',
    dateHijri: getCurrentHijriDate(),
    dateGregorian: getCurrentGregorianDate(),
    amount: 150000,
    amountWords: 'مائة وخمسون ألف ريال يمني فقط لا غير',
    beneficiaryName: 'محمد احمد علي وشركاه للتجارة العامة',
    purpose: 'قيمة شراء قطع غيار وزيوت وفلاتر لآليات ومعدات النظافة الميدانية الخاصة بقطاع النظافة العامة',
    notes: 'مرفق أصل فاتورة الشراء وسند الاستلام الفني للقطع',
    status: 'APPROVED',
    attachmentsCount: 2,
    tags: ['صيانة', 'قطع غيار', 'نظافة'],
    managerName: 'رياض احمد محمد',
    financeManagerName: '',
    treasurerName: '',
    createdAt: Date.now() - 86400000 * 2,
  },
  {
    id: 'doc-2',
    type: 'REQUEST',
    documentNumber: '0002',
    dateHijri: getCurrentHijriDate(),
    dateGregorian: getCurrentGregorianDate(),
    amount: 95000,
    amountWords: 'خمسة وتسعون ألف ريال يمني فقط لا غير',
    beneficiaryName: 'إدارة الحركة وصيانة المعدات',
    requesterName: '',
    purpose: 'طلب شراء أدوات ومستلزمات وقائية وكمامات لعمال النظافة الميدانيين لشهر سبتمبر',
    details: 'شراء عدد 40 مكنسة شوارع يدوية، 60 زوج قفازات جلدية، و100 كرتون أكياس نفايات متينة للمربعات الميدانية',
    notes: 'مرفق كشف الاحتياج المعتمد من مشرفي القطاعات الميدانية',
    status: 'SUBMITTED',
    attachmentsCount: 1,
    tags: ['نظافة', 'معدات'],
    managerName: 'رياض احمد محمد',
    createdAt: Date.now() - 86400000,
  },
  {
    id: 'doc-3',
    type: 'RECEIPT',
    documentNumber: '0003',
    dateHijri: getCurrentHijriDate(),
    dateGregorian: getCurrentGregorianDate(),
    amount: 120000,
    amountWords: 'مائة وعشرون ألف ريال يمني فقط لا غير',
    beneficiaryName: 'عبده صالح محمد القادري',
    jobTitle: 'سائق معدات وآليات نظافة ميدانية',
    purpose: 'استلام كامل مستحقات أجور صيانة ومكافأة النوبة الإضافية لرفع المخلفات',
    monthPeriod: 'سبتمبر',
    yearHijri: '6',
    yearGregorian: '6',
    notes: 'بطاقة شخصية رقم: 01020304050 - هاتف: 771234567',
    status: 'PAID',
    attachmentsCount: 1,
    tags: ['رواتب', 'أجور عمال'],
    managerName: 'رياض احمد محمد',
    financeManagerName: '',
    treasurerName: '',
    createdAt: Date.now() - 3600000 * 5,
  },
  {
    id: 'doc-4',
    type: 'ORDER',
    documentNumber: '0004',
    dateHijri: getCurrentHijriDate(),
    dateGregorian: getCurrentGregorianDate(),
    amount: 65000,
    amountWords: 'خمسة وستون ألف ريال يمني فقط لا غير',
    beneficiaryName: 'المؤسسة العامة للكهرباء - منطقة إب',
    purpose: 'سداد فاتورة استهلاك التيار الكهربائي لمقر إدارة الفرع وغرف العمليات الميدانية',
    notes: 'مرفق أصل فاتورة الاستهلاك رقم 887654',
    status: 'APPROVED',
    attachmentsCount: 1,
    tags: ['كهرباء', 'صيانة'],
    managerName: 'رياض احمد محمد',
    financeManagerName: '',
    treasurerName: '',
    createdAt: Date.now() - 3600000 * 2,
  },
];
